### ISSUE TITLE
Integrating with trapz?

### ISSUE THREAD

**Issue by dhirschfeld** [IPGP/scientific_python_cheat_sheet#11]
Shouldn't the default integrator be `quad`? Is `trapz` actually used much in practice excepting for _possibly_ pedagogical purposes. I've never found the need for it but have used `quad` extensively.

**Comment by MMesch** [comment]
`quad` is a `scipy` function, `trapz` is numpy. So far we didn't put any scipy functions to keep things simple. A few well-selected scipy functions would be nice on the other hand. The question is whether we should put them in a joint category with numpy or in a new one. I am personally for a mixed category that covers the most common scientific needs...

**Comment by dhirschfeld** [comment]
The name _is_ scientific Python and it is including stuff from matplotlib and even IPython so I would've expected scipy functions to make the cut! It would be nice If it were a good quick-reference for general-purpose, best-of-breed implementations. I appreciate that that may significantly increase the scope though. 

The sections included `interpolation/integration/fft` are probably the most problematic  as they overlap with scipy but have hidden pitfalls in that they're either significantly less functional or less performant (IIRC).

A mixed category would probably be a good resolution as it could provide the more fully-featured / performant implementations for those who don't mind a dependency on scipy.

**Comment by MMesch** [comment]
I agree fully! I'll try to rearrange the website to make some space for more sections without loss of clarity. Then we can open a mixed section...

**Comment by MMesch** [comment]
there is an (almost empty) scipy section now that can be filled. I think it would be nice if the user can select with some clicks which of the modules he wants to see in the overview. Also we should certainly not display the whole scipy library. The official documentation is way better for this. Only functions that are **often** used. Of course this depends on the user, but I am thinking about splines, optimization and stuff like this...

**Comment by MMesch** [comment]
we can later decide to make a mixed section. For now I think it is good to have them separate until we figure out, which scipy functions should be used when possible...
